
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
// Fixed: Removed ServiceType from lucide-react import as it's not a member of the library and is unused in this file.
import { Search, Loader2, Bot, ArrowRight } from 'lucide-react';
import { geminiService } from '../services/geminiService';
import { Link } from 'react-router-dom';

const SearchPage: React.FC = () => {
  const [query, setQuery] = useState('');
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;
    setLoading(true);
    const response = await geminiService.getAdvice(
      `The user is searching the KAT Group website for: "${query}". Provide a concise summary of how KAT Group handles this and which service they should look at.`,
      []
    );
    setResult(response);
    setLoading(false);
  };

  return (
    <div className="pt-32 min-h-screen bg-white">
      <div className="max-w-4xl mx-auto px-6">
        <div className="text-center mb-16">
          <motion.div 
            initial={{ scale: 0.8, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="w-20 h-20 bg-blue-600 rounded-[2rem] flex items-center justify-center text-white shadow-2xl mx-auto mb-8"
          >
            <Bot className="w-10 h-10" />
          </motion.div>
          <h1 className="text-5xl font-heading font-black text-slate-900 tracking-tighter mb-4">Semantic Discovery</h1>
          <p className="text-slate-500 font-light">Ask our AI anything about our industrial capabilities.</p>
        </div>

        <form onSubmit={handleSearch} className="relative mb-20">
          <input 
            type="text" 
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="e.g. How do you handle offshore safety in Oil & Gas?"
            className="w-full pl-10 pr-20 py-8 bg-slate-50 rounded-[2.5rem] border-none focus:ring-4 focus:ring-blue-500/10 outline-none text-xl font-light transition-all shadow-sm"
          />
          <button 
            type="submit"
            className="absolute right-4 top-1/2 -translate-y-1/2 bg-[#0a1d4d] text-white p-5 rounded-full hover:scale-105 transition-all shadow-xl"
          >
            {loading ? <Loader2 className="w-6 h-6 animate-spin" /> : <Search className="w-6 h-6" />}
          </button>
        </form>

        <AnimatePresence>
          {result && (
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-[#0a1d4d] rounded-[3rem] p-12 text-white shadow-2xl relative overflow-hidden"
            >
              <div className="absolute top-0 right-0 p-8 opacity-10">
                <Bot className="w-32 h-32" />
              </div>
              <h3 className="text-blue-400 font-black uppercase tracking-[0.3em] text-[10px] mb-6">AI Insight</h3>
              <div className="prose prose-invert prose-lg max-w-none font-light leading-relaxed">
                {result}
              </div>
              <div className="mt-12 pt-8 border-t border-white/10 flex items-center justify-between">
                <span className="text-slate-400 text-xs italic">Generated by Gemini AI Advisor</span>
                <Link to="/contact" className="flex items-center gap-2 text-white font-bold hover:text-blue-400 transition-colors">
                  Speak to an Expert <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <div className="mt-20 grid grid-cols-1 md:grid-cols-2 gap-8 mb-32">
          <div className="p-8 rounded-[2rem] bg-slate-50 border border-slate-100">
             <h4 className="font-bold text-slate-900 mb-4">Popular Searches</h4>
             <ul className="space-y-3 text-sm text-slate-500">
               <li className="flex items-center gap-2 cursor-pointer hover:text-blue-600 transition-colors">
                 <Search className="w-3 h-3" /> MEP Services in Dubai
               </li>
               <li className="flex items-center gap-2 cursor-pointer hover:text-blue-600 transition-colors">
                 <Search className="w-3 h-3" /> Healthcare staffing compliance
               </li>
               <li className="flex items-center gap-2 cursor-pointer hover:text-blue-600 transition-colors">
                 <Search className="w-3 h-3" /> Mass recruitment for manufacturing
               </li>
             </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SearchPage;
